version: '3'
services:
  suzumechat_local_postgres:
    container_name: suzumechat_local_postgres
    image: postgres:14
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: suzumechat_local_db
      POSTGRES_USER: suzumechat
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  suzumechat_local_redis:
    container_name: suzumechat_local_redis
    image: redis:latest
    ports:
      - 6379:6379
  # uncomment when you test dockernized app locally
  # suzumechat_app:
  #   image: suzumechat-backend-local
  #   ports:
  #     - 8010:8080
  #   depends_on:
  #     - suzumechat_local_postgres
  #     - suzumechat_local_redis
  #   environment:
  #     - LOCAL_CONTAINER_DB_URL=jdbc:postgresql://suzumechat_local_postgres:5432/suzumechat_local_db
  #     - LOCAL_CONTAINER_REDIS=suzumechat_local_redis

